### ISSUE TITLE
Cross-platform support. 

### ISSUE THREAD

**Issue by sheridanchris** [thinkbeforecoding/Fargo#1]
These imports break Fargo on non-windows machines.

```fsharp
[<DllImport("kernel32.dll", SetLastError=true)>]
extern bool GetConsoleMode(IntPtr hConsoleHandle , uint32& lpMode) 
[<DllImport("kernel32.dll", SetLastError=true)>]
extern IntPtr GetStdHandle(int nStdHandle)
[<DllImport("kernel32.dll", SetLastError=true)>]
extern bool SetConsoleMode(IntPtr hConsoleHandle, uint32 dwMode )
```

**Comment by thinkbeforecoding** [comment]
Right, I can probably skip it enterly on other platforms

**Comment by sheridanchris** [comment]
I'd like to PR this. Should `supportVT100` return `true` or `false` on Linux and MacOS. I'm thinking `true` as most modern terminal emulators support ANSI color codes.

**Comment by thinkbeforecoding** [comment]
😊 Thank you!
I should probably return true. This way it would use vt100 codes for display
