### ISSUE TITLE
Nuget release to downgrade required FSharp.Core?

### ISSUE THREAD

**Issue by njlr** [thinkbeforecoding/Fargo#11]
I am trying to use Fargo in a .NET 6 project, which is not possible due to conflicting requirements on `FSharp.Core`. 

The [latest on Nuget](https://www.nuget.org/packages/Fargo.CmdLine/1.1.14#dependencies-body-tab) requires `FSharp.Core` `(>= 7.0.400)`

However, I see in the `paket.dependencies` that only `>= 6.0` is needed: https://github.com/thinkbeforecoding/Fargo/blob/main/paket.dependencies#L5

Perhaps another release is required to make this work?

**Comment by Numpsy** [comment]
> I am trying to use Fargo in a .NET 6 project, which is not possible due to conflicting requirements

fwiw I'm using it in a .NET 6 .NET Global tool project OK, though FSharp.Core is bundled into the tool package anyway so maybe it's a different situation.
A new build to get #7 would be nice if possible though :-)

**Comment by njlr** [comment]
Gentle bump on this :slightly_smiling_face:

**Comment by njlr** [comment]
@thinkbeforecoding Please can you trigger a release?

**Comment by thinkbeforecoding** [comment]
Released as v1.3.3 👍
