### ISSUE TITLE
Custom operators

### ISSUE THREAD

**Issue by ChrSteinert** [thinkbeforecoding/Fargo#3]
Not so much an issue – I just want do make you aware, that other libraries, like [FParsec](https://www.quanttec.com/fparsec/reference/parser-overview.html#:~:text=of%20the%20input.-,Table%206.1.6,-%3A%20Chaining%20and), already has some custom operators "established".
When I was reading the doc I thought "oh cool, the `<|>` operator of alternatives, just like in FParsec". Seeing familiar operators for similar things just seem nice.

That is not to tell you how to make your operators (and explicitly not to change an already set one)! All I want is to take the FParsec operators as a datapoint going forward.

Please simply close this "issue" once you have had a look at the other operators.

Thanks

**Comment by thinkbeforecoding** [comment]
Yes, which other operator are you thinking of ?
I use the `<|>` and `|>>` operator from FParsec. Feel free to tel me if you see other that are missing and could be useful.

**Comment by ChrSteinert** [comment]
Ah – I see you just changed my main concern `|~>` into `|>>` in b6c8c6684e52e2d60280066e349f8c9600e0edfb ;)
That would only let `>>%` and `>>=` left. Though I am not sure, if they would add much to the library overall.

Anyway – not having `|~>` anymore makes me more than satisfied and I'm going to close this. :)

Thanks!
